### PR TITLE
bleeeeeerg

### PR DESCRIPTION
**Pull request by bcardarella**

### CODE REVIEW

**Comment by danmcclain** [comment]
:+1: For descriptive commit message :trollface:

**Comment by bcardarella** [comment]
There is no correlation between writing blog posts and commit messages

**Comment by danmcclain** [comment]
Thank god :smile: 

On a less troll-y note, this looks good :+1:

**Comment by michaeldupuisjr** [comment]
Looks good to me.

**Comment by brzpegasus** [comment]
I approve this message.

**Pull request merged**
