### PR TITLE
Add post on image upload API - Publish Tuesday, 8/22

### PR DESCRIPTION
**Pull request by alexgaribay**

### CODE REVIEW

**Comment by chrismccord** [comment]
What do you think about a broader module name that can wrap up more functionality. For example, if we were to split out our uploader feature to its own app, we'd name it something more specific like `FileStore` or `AssetStore`.

So I would rename to something along those lines and expose a `FileStore.upload_image/1` function in the post. Thoughts?

We also may want to use Plug.Upload instead of a base64 encoded image. I think a very large encoded image can be costly, but for the purpose of the guide it may be okay.

**Comment by alexgaribay** [comment]
> So I would rename to something along those lines and expose a FileStore.upload_image/1 function in the post. Thoughts?

A more generic name for the module is okay to me.

> We also may want to use Plug.Upload instead of a base64 encoded image. I think a very large encoded image can be costly, but for the purpose of the guide it may be okay.

Can Plug.Upload even be used here? I know it works for file uploads through forms but I didn't know if it could apply to file uploads. As for my example, it's relevant to how we are doing it on DY-API now with base64 encodings.

**Comment by chrismccord** [comment]
Ah good point, this is api specific. Plug.Upload would only work provided the correct headers are set. It could be made it work in your curl example, but not sure from js client perspective

**Comment by alexgaribay** [comment]
What should I make the target date?

**Comment by bcardarella** [comment]
@alexgaribay Estelle and Jessica are coming up with that

**Comment by jesskry** [comment]
@bcardarella I actually rename them now when I ask for them to be published. I'll take care of this. @alexgaribay is this post final?

**Comment by alexgaribay** [comment]
@jesskry, assuming the reviews are okay, then yes.

**Comment by jesskry** [comment]
@alexgaribay Can you add an image at the top? Then we can post this today. Thx.

**Pull request merged**
